# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_normal <- function(mu, Sigma_inv) {
    .Call('zoofactr_draw_normal', PACKAGE = 'zoofactr', mu, Sigma_inv)
}

density_normal <- function(x, mu, Sigma_inv, logret = FALSE) {
    .Call('zoofactr_density_normal', PACKAGE = 'zoofactr', x, mu, Sigma_inv, logret)
}

draw_wishart <- function(v, S) {
    .Call('zoofactr_draw_wishart', PACKAGE = 'zoofactr', v, S)
}

log_mv_gamma <- function(p, a) {
    .Call('zoofactr_log_mv_gamma', PACKAGE = 'zoofactr', p, a)
}

density_wishart <- function(X, v, S, logret = FALSE) {
    .Call('zoofactr_density_wishart', PACKAGE = 'zoofactr', X, v, S, logret)
}

vech <- function(A) {
    .Call('zoofactr_vech', PACKAGE = 'zoofactr', A)
}

devech <- function(v, dim) {
    .Call('zoofactr_devech', PACKAGE = 'zoofactr', v, dim)
}

rcpp_hello <- function() {
    .Call('zoofactr_rcpp_hello', PACKAGE = 'zoofactr')
}

samplerTest <- function(X, Y, G0, g0, R0, r0, n_draws, burn_in) {
    .Call('zoofactr_samplerTest', PACKAGE = 'zoofactr', X, Y, G0, g0, R0, r0, n_draws, burn_in)
}

